pipeline:
  name: FIS_Demo
  identifier: FIS_Demo
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deployment
        identifier: Deployment
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: FISdemo
          environment:
            environmentRef: harnessdevenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: Helminfra
          execution:
            steps:
              - step:
                  type: HelmDeploy
                  name: HelmDeploy_1
                  identifier: HelmDeploy_1
                  spec:
                    skipDryRun: false
                    ignoreReleaseHistFailStatus: false
                    delegateSelectors:
                      - kubernetes-delegate
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        delegateSelectors:
          - kubernetes-delegate
        failureStrategies:
          - onFailure:
              errors:
                - Unknown
              action:
                type: Abort
