service:
    name: webapp
    identifier: webapp
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: webapp
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: webappgitconnector
                            gitFetchType: Branch
                            paths:
                                - web_service.yaml
                                - deployment.yaml
                            repoName: Web
                            branch: main
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
    gitOpsEnabled: false
